const COULD_NOT_CREATE_ACCOUNT = 1100;
const CREATED_ACCOUNT = 1101;
const ALREADY_CREATED_ACCOUNT = 1102;
const TOKEN_VERIFIED = 1103;
const TOKEN_NOT_VERIFIED = 1104;
const NULL_TOKEN = 1105;
const COULD_NOT_FETCH = 1106;
const FETCHED = 1107;
const ACCONT_CREATED = 1108;
const DATA_UPDATED = 1109;
const DATA_NOT_UPDATED = 1110;
const ERROR_IN_MIDDLEWARE = 1111;

const HOST_URL_IS_NOT_ENABLED = 1300;
const NOT_ALLOWED_TO_USE_THIS_URL=1301;
const UN_AUTHORIZED_TO_PERFORM_OPERATION=1302;
const INVALID_OPERATION_KEY_WORDS_IN_QUERY=1303;


module.exports = {
  ERROR_IN_MIDDLEWARE,
  COULD_NOT_CREATE_ACCOUNT,
  CREATED_ACCOUNT,
  ALREADY_CREATED_ACCOUNT,
  TOKEN_VERIFIED,
  TOKEN_NOT_VERIFIED,
  NULL_TOKEN,
  COULD_NOT_FETCH,
  FETCHED,
  ACCONT_CREATED,
  DATA_UPDATED,
  DATA_NOT_UPDATED,



  //request statuses
  HOST_URL_IS_NOT_ENABLED,
  NOT_ALLOWED_TO_USE_THIS_URL,
  UN_AUTHORIZED_TO_PERFORM_OPERATION,
  INVALID_OPERATION_KEY_WORDS_IN_QUERY
};
